vmware-samples/vmware-blockchain-samples

- HANDSON.md
- README.md
- contracts/OrdersV2.sol
- docker-compose.yml
- migrations/2_initial_deploy.js
- src/app/core/blockchain/blockchain.service.ts
- src/app/home/blockchain-status/blockchain-status.component.ts
- src/app/home/create-order/create-order.component.html
- src/app/home/create-order/create-order.component.ts
- src/app/home/home.component.html
- src/app/home/home.component.ts
- src/app/home/order-detail/order-detail.component.html
- src/app/home/order-detail/order-detail.component.ts
- src/app/shared/global-alert.service.spec.ts
- src/app/shared/global-alert.service.ts
- src/app/shared/shared.module.ts
- truffle-config.js
- Various fixes and updates so that the hands on works
> Hands On Document

- HANDSON.md
- README.md
- Update README
- Update HANDSON
> Accidentally overwrite Tasnim’s Readme update

- Dockerfile
- HANDSON.md
- README.md
- src/app/core/user/user.service.ts
- src/app/shared/toggle-radio-group/toggle-radio-group.component.html
- src/app/shared/toggle-radio-group/toggle-radio-group.component.ts
Update hands for correct versioning migration
Add ssh tunneling help to README
HANDSON add docker-compose to truffle console
Always select farmer on page load
> Fixed Versioning Handson, etc.

- HANDSON.md
- demo_data/large.json
- demo_data/medium.json
- demo_data/small.json
- docker-compose.yml
- src/app/core/blockchain/blockchain.service.ts
> Update storage hands on and add demo_data

- src/app/core/blockchain/blockchain.service.ts
> Remove console log

- src/app/core/blockchain/blockchain.service.ts
- src/environments/environment.vmware-dev.ts
- Relative path to avoid deployment issues on servers
- Switched back to inEvent storage
> Relative path for vmware blockchain

- README.md
- docker-compose-local-network.yml
- docker-compose.yml
- package.json
- Create local network yaml for using supply chain with a locally deployed blockchain
> Build instead of pull with docker compose

- README.md
> Add Root README for VMware Blockchain Samples

- supply-chain/verify/README.md
- supply-chain/verify/flatten.sh
- supply-chain/verify/verify.js
* Add a timestamp as a suffix to verify contract
* Create truffle-flattener folder and flatten contract
> VB-846 Contracts are being removed or being added to a version

- supply-chain/Dockerfile
Signed-off-by: Abhijit Mande <mandeab@vmware.com>
> Including truffle-flattener install in Dockerfile

- supply-chain/Dockerfile
Signed-off-by: Abhijit Mande <mandeab@vmware.com>
> Adding version to truffle-flattener

- asset-transfer/AssetTransfer.js
Signed-off-by: Abhijit Mande <mandeab@vmware.com>
> Bugfix in AssetTransfer.js

- asset-transfer/test/test_AssetTransfer.js
Reverts vmware-samples/vmware-blockchain-samples#37
> Revert "Replaced Test #3 with two other tests"

- asset-transfer/test/test_AssetTransfer.js
This reverts commit 18191091053018fa036e0413c294ba4e2c9f150a.
Adding back the two other tests that were removed.
Signed-off-by: Abhijit Mande <mandeab@vmware.com>
> Revert "Revert "Replaced Test #3 with two other tests""

- asset-transfer/Dockerfile
Signed off by: Abhijit Mande <mandeab@vmware.com>
> Change dockerfile

- supply-chain/README.md
- supply-chain/docker-compose.yml
- supply-chain/src/app/auth/auth.service.ts
- supply-chain/src/app/core/blockchain/blockchain.service.ts
- supply-chain/truffle-config.js
Reverts vmware-samples/vmware-blockchain-samples#43
> Revert "Documentation and code fixes enabling the Supply Chain demo to run against VMware Blockchain"

- supply-chain/angular.json
- supply-chain/package.json
- supply-chain/proxy.conf.js
- supply-chain/src/app/auth/auth.guard.ts
- supply-chain/src/app/core/blockchain/blockchain.service.ts
- supply-chain/src/app/core/blockchain/blockchain.ts
- supply-chain/src/environments/environment.concord-dev.ts
- supply-chain/truffle-config.js
- Adding configuration in order to get concord working
> Add Concord Configuration

- obp/docker-compose.yml
- obp/package.json
> expose port for obp

- web3j/src/main/java/com/vmware/ethereum/config/AppConfig.java
- web3j/src/main/java/com/vmware/ethereum/config/Web3jConfig.java
- web3j/src/main/java/com/vmware/ethereum/controller/MainController.java
- web3j/src/main/java/com/vmware/ethereum/service/ClosedWorkload.java
- web3j/src/main/java/com/vmware/ethereum/service/OpenWorkload.java
- web3j/src/main/java/com/vmware/ethereum/service/SecureTokenApi.java
- web3j/src/main/java/com/vmware/ethereum/service/WorkloadCommand.java
- web3j/src/main/java/com/vmware/ethereum/service/WorkloadRunner.java
- web3j/src/main/resources/config/application.yml
Miscellaneous improvements including
- Configurable chain id
- Configurable receipt polling interval
- Nonce management
- Async with CompletableFuture
> Benchmark improvements

- web3j/README.md
- web3j/pom.xml
- web3j/src/main/java/com/vmware/ethereum/LoadRunner.java
- web3j/src/main/java/com/vmware/ethereum/config/AppConfig.java
- web3j/src/main/java/com/vmware/ethereum/service/ClosedWorkload.java
- web3j/src/main/java/com/vmware/ethereum/service/MetricsConstant.java
- web3j/src/main/java/com/vmware/ethereum/service/MetricsService.java
- web3j/src/main/java/com/vmware/ethereum/service/ProgressService.java
- web3j/src/main/java/com/vmware/ethereum/service/TimedWrapper.java
- web3j/src/main/java/com/vmware/ethereum/service/WorkloadRunner.java
- web3j/src/main/resources/config/application.yml
- web3j/src/main/resources/static/js/progress.js
- web3j/src/main/resources/templates/report.html
Signed-off-by: Dharmaraj Parmar <dharmaraj.parmar@gmail.com>
> Squashed into one.

- web3j/src/main/java/com/vmware/ethereum/service/CurrentMetrics.java
- web3j/src/main/java/com/vmware/ethereum/service/MetricsConstant.java
- web3j/src/main/java/com/vmware/ethereum/service/MetricsService.java
- web3j/src/main/resources/config/application.yml
- web3j/src/main/resources/templates/report.html
- Fixed an issue (current throughput sometimes shows 0) reported by Dheeraj
- Made some cosmetic changes in progress page so the summary doesn't move to next row.
> Fixed current throughput calculation

- supply-chain/contracts/OrderV1.sol
- supply-chain/src/app/core/blockchain/blockchain.service.ts
- Storing documents wasn't working due to precompiled contract issue and updated evm on VMware blockchain
- Moving document creation to same time order is created
> Fix doc store

- web3py/lrt-examples/eth-simple.py
- web3py/lrt-examples/eth.py
Signed-off-by: ramki krishnan <ramkik@vmware.com>
> tests for unsigned transactions

- web3py/lrt-examples/eth.py
Signed-off-by: ramki krishnan <ramkik@vmware.com>
> eth api gaps

- web3py/lrt-examples/eth.py
Signed-off-by: ramki krishnan <ramkik@vmware.com>
> added simples tests for estimate gas and filter logs

- web3j/src/main/java/com/vmware/ethereum/service/SecureTokenApi.java
- web3j/src/main/java/com/vmware/ethereum/service/WorkloadCommand.java
- Now queuedTransfer function call are asynchronous 
- better exception throwing for deferred polling
> Deferred Polling - Async call for queuedTransfer

- web3j/pom.xml
- web3j/src/main/java/com/vmware/ethereum/config/TokenConfig.java
- web3j/src/main/java/com/vmware/ethereum/model/ProgressReport.java
- web3j/src/main/java/com/vmware/ethereum/service/ProgressService.java
- web3j/src/main/java/com/vmware/ethereum/service/SecureTokenApi.java
- web3j/src/main/java/com/vmware/ethereum/service/WorkloadCommand.java
- web3j/src/main/java/com/vmware/ethereum/service/WorkloadRunner.java
- web3j/src/main/resources/config/application.yml
- web3j/src/main/resources/static/js/progress.js
- web3j/src/main/resources/templates/report.html
added support to load ERC20 smart contract from the given address.
> ERC20 contract loading

- web3j/pom.xml
- web3j/src/main/java/com/vmware/ethereum/config/DatabaseConfig.java
- web3j/src/main/java/com/vmware/ethereum/model/Contract.java
- web3j/src/main/java/com/vmware/ethereum/service/SecureTokenApi.java
- web3j/src/main/resources/config/application.yml
Postgres integration using sql2o 
ERC20 now can pick contract addresses from database
> PostgreSQL integration with ERC20 (sql2o)

- erc20-load-test-tool/src/main/java/com/vmware/ethereum/model/ProgressReport.java
- erc20-load-test-tool/src/main/java/com/vmware/ethereum/service/ProgressService.java
- erc20-load-test-tool/src/main/resources/config/application.yml
- erc20-load-test-tool/src/main/resources/static/js/progress.js
- erc20-load-test-tool/src/main/resources/templates/report.html
Added function to save logs to file
Removed account balance from UI
> Save logs to file - ERC20 tool

- erc20-load-test-tool/script/run-dapp.py
- erc20-load-test-tool/src/main/java/com/vmware/ethereum/config/AppConfig.java
- erc20-load-test-tool/src/main/java/com/vmware/ethereum/model/ProgressReport.java
- erc20-load-test-tool/src/main/java/com/vmware/ethereum/service/MetricsConstant.java
- erc20-load-test-tool/src/main/java/com/vmware/ethereum/service/MetricsService.java
- erc20-load-test-tool/src/main/java/com/vmware/ethereum/service/ProgressService.java
- erc20-load-test-tool/src/main/java/com/vmware/ethereum/service/WorkloadCommand.java
- erc20-load-test-tool/src/main/java/com/vmware/ethereum/service/WorkloadRunner.java
- erc20-load-test-tool/src/main/resources/static/js/progress.js
- erc20-load-test-tool/src/main/resources/templates/report.html
> ERC20: Read/Write Request Throughput

- vmbc-ethereum-starter-kit/release-1.6/starter-kit/README.txt
- vmbc-ethereum-starter-kit/release-1.6/starter-kit/dapp/k8s-dapp-destroy.sh
- vmbc-ethereum-starter-kit/release-1.6/starter-kit/dapp/k8s-dapp-launch.sh
- vmbc-ethereum-starter-kit/release-1.6/starter-kit/explorer/k8s-explorer-destroy.sh
- vmbc-ethereum-starter-kit/release-1.6/starter-kit/explorer/k8s-explorer-launch.sh
Updated namespace for explorer and DAPP.
> Update Pre-requisites for starter kit

- vmbc-ethereum-starter-kit/release-1.6/starter-kit/minikube/minikube-start.sh
Set 4 CPU and 12GB memory for minikube
> CPU and memory settings for minikube

- vmbc-ethereum-starter-kit/release-1.6/starter-kit/README.md
- vmbc-ethereum-starter-kit/release-1.6/starter-kit/minikube/minikube-delete.sh
- vmbc-ethereum-starter-kit/release-1.6/starter-kit/minikube/minikube-start.sh
Signed-off-by: Rahul Agarwal <agarwalrahul@vmware.com>
> Update readme instructions with minikube details

- artemis/clarity/ganymede.app.ts
- artemis/clarity/package-lock.json
- artemis/clarity/package.json
- artemis/clarity/src/app/app-routing.module.ts
- artemis/clarity/src/app/http.wrapper.ts
- artemis/clarity/src/app/main/digital-arts.service.ts
- artemis/clarity/src/app/main/ethereum.service.ts
- artemis/clarity/src/app/main/models/digital-art.model.ts
- artemis/clarity/src/app/main/test-mock.data.ts
- artemis/clarity/src/app/main/test-runner.service.ts
- artemis/clarity/src/app/routes/digital-arts/digital-arts-details/digital-arts-details.component.html
- artemis/clarity/src/app/routes/digital-arts/digital-arts-details/digital-arts-details.component.scss
- artemis/clarity/src/app/routes/digital-arts/digital-arts-details/digital-arts-details.component.ts
- artemis/clarity/src/app/routes/digital-arts/digital-arts-grid/digital-arts-grid.component.html
- artemis/clarity/src/app/routes/digital-arts/digital-arts.component.html
- artemis/clarity/src/app/routes/digital-arts/digital-arts.component.scss
- artemis/clarity/src/app/routes/digital-arts/digital-arts.component.ts
- artemis/clarity/src/app/routes/landing/landing.component.html
- artemis/clarity/src/app/routes/landing/landing.component.ts
- artemis/clarity/src/app/routes/mock-settings/mock-settings.component.html
- artemis/clarity/src/app/routes/utils/account-gen/account-gen.component.html
- artemis/clarity/src/app/routes/utils/account-gen/account-gen.component.ts
- artemis/clarity/src/app/routes/utils/god-account/god-account.component.ts
- artemis/clarity/src/app/routes/utils/utils.component.ts
- Migrating from Web3js to Ethers.js
- Updating some UI and functionality
- Additional formatting and comments
> Migrating from Web3js to Ethers.js

- artemis/clarity/src/app/main/ethereum.service.ts
- artemis/clarity/src/app/main/test-runner.service.ts
Signed-off-by: Kevin Xu <kevinx1@vmware.com>
> Letting User Account Mock Tests

- vmbc-ethereum/block-explorers/sirato-explorer/README.md
Fix typo and update structure.
> Update Sirato docs
